### ISSUE TITLE
Init

### ISSUE THREAD

**Issue by tomasfejfar** [keboola/app-snowflake-dwh-manager#1]
Z https://github.com/keboola/internal/issues/10#issuecomment-392744572:

Bavili jsme se o tom teď s najlošem a už jsem pochopil jak to myslel myslím že to dává dost smysl, zkusím to sepsat.

Appka by zajištovala kompletní správu business schemát a k nim přsistupujícím userům kterým by zároveň poskytla pracovní schéma. Aplikace neřeší zakládání KBC projektů ale jenom správu SNFLK. O předání credentials se musí uživatelé postarat sami.

Konfigurace by vypadala následnovně:

## config
 - snowflake host, user, password, database - master credentials uživatele který je owner předávané prázdné databáze. Uživatel musí mít navíc práva na vytváření uživatelů a rolí.
  - snowflake warehouse - warehouse který budou uživatelé používat. master credentials musí mít práva na jeho usage grantovatelné dále

## config rows
V každém row bude popsano co má ve SNFLK být vytvořeno. Buď business schéma nebo user.
Je to stavové, appka si ke každému row poznamená do state jestli entitu už vytvořila a při znovu spuštění už to jenom přeskočí. Případně zjistí zda došlo k nějakým změnám a provede je.

### Business schema
Vytvoří schéma + uživatele z write právy. Jeho username a jednorázové heslo vrátí to event. Tento uživatel bude sloužít pro zápis do business schématu SNFLK writerem z libovolného projektu, je to ok? Zároveň vytvoří RO roli pro přístup k tomuto schématu.

Při znovu spuštění zároveň vždy i když nedošlo k žádným změnám refreshne práva RO role na přístup k tabulkám. Je to potřeba v případě že writer zapsal nové tabulky.

**Parametry**
- jméno schématu

### Uživatel (analytik)
Vytvoří uživatele, jeho pracovní schéma, roli která bude mít plná práva nad pracovním schématem a bude mít grantutém read-only role business schémat které budou uživatele přiřazeny.

**Parametry**
- email uživatele
- jména business schémat - jména business schémat ke kterým má mít RO přístup 
- disabled - bude umožnovat uživatele a jeho resources smazat

# Použití

## Přidání nového uživatele
- Přidá se nový config row typu user a vyplní se jméno email uživatele a vyberou se schémata ke kterým má mít RO přístup
- Spustí se konfigurace
- V logu jobu jsou k dispozici dočasné credentials nového uživatele

## Přidání business schématu
- Přidá se config row typu schema a vyplní se jeho jméno (vše co povoluje SNFLK)
- Spustí se konfigurace
- V logu jobu jsou zároveň dočasné writer credentials uživatele schématu

**Comment by ondrejhlavacek** [comment]
Rychlá poznámka z mobilu - může to bejt bezstavový (ideálně), jmenný konvence a metadata v Snowflake nahradí state.

**Comment by tomasfejfar** [comment]
Jestli to chápu správně... zkontroluje to, jestli je všechno tak jak má být. A pokud ne, tak to udělá. Nebude si to ukládat, že to udělalo (protože to mohl někdo rozbít mezi tím).

**Comment by ondrejhlavacek** [comment]
Přesně. Nějaký metadata dotazy jsou na Snowflake děsně pomalý, ale Martin snad někde psal (a nebo ví) jak na ně.

**Comment by tomasfejfar** [comment]
Ale to by tady nemuselo ničemu vadit. Nebude se to spouštět nějak extra často, ne?

**Comment by tomasfejfar** [comment]
@Halama máš někde ty rychlejší dotazy? 

Zkusil jsem `SELECT * FROM INFORMATION_SCHEMA.OBJECT_PRIVILEGES WHERE OBJECT_NAME LIKE 'TF%';` a trvá 6.63s z UI vč. všeho, samotné execution 2.11s.

**Comment by Halama** [comment]
rychlejší dotazy asi nemám. Co přesně potřebuješ zjištovat?

**Comment by tomasfejfar** [comment]
Potřebuju zjistit, že tam jsou schémata, role, uživatelé a že jim sedí granty tak jak mají.

**Comment by Halama** [comment]
`show grants to role sapi_workspace_497413;` mi chodí bleskově.  `show databases;` také.  `show users` potřebuje větší práva https://docs.snowflake.net/manuals/sql-reference/sql/show-users.html to možná bude problém, chce to prozkoumat. Možná by se to dalo obejít tak že ho vždy zkusí vytvořit s `CREATE USER IF NOT EXISTS`.

`show roles;` je jediný pomalý a s tím asi nic neuděláme, můžeme možná hodit na support.

**Comment by tomasfejfar** [comment]
Obecně tam bude koukám problém s vytvářením globálních věcí (rolí a userů). Udělal jsem si omezeného usera jen na tu DB a s tím to nejde. Budu mu muset dát větší práva na správnu userů. 

```
root@910f8801a1a5:/code# php src/run.php
Schema "my-dwh-schema" exists
Role "my-dwh-schema" exists
Role "my-dwh-schema" has all the required grants
Created schema "my-dwh-schema"
[2018-06-11 16:11:29] CRITICAL: ErrorException:odbc_prepare(): SQL error: SQL access control error: Insufficient privileges to operate on account 'KEBOOLADEV', SQL state 42501 in SQLPrepare 
```

**Comment by Halama** [comment]
Myslím si že ta role uživatele appky by měla vypadat takhle:
```
CREATE ROLE dwh_master;
GRANT OWNERSHIP ON DATABASE  dwh TO ROLE dwh_master;
GRANT CREATE ROLE, CREATE USER ON ACCOUNT TO ROLE dwh_master;
```

**Comment by tomasfejfar** [comment]
No, ale tím může vytvářet obecně jakékoli role a uživatele, ne?

**Comment by Halama** [comment]
jo ale tomu se nevyhneme. Musí to všechno něčím prefixovat.
