### ISSUE TITLE
Allow to add schema as read/write opposed to read-only

### ISSUE THREAD

**Issue by tomasfejfar** [keboola/app-snowflake-dwh-manager#13]
Required for #12 (specifically https://github.com/keboola/app-snowflake-dwh-manager/issues/12#issuecomment-416025397)

Currently users only get read-only access to created schemas (and read-write to their own schema). New feature should allow admin to add read-write access to schema as well. That should be reflected in the UI as well.

**Comment by Halama** [comment]
Byl ten 1. bod [tady](https://github.com/keboola/app-snowflake-dwh-manager/issues/12#issuecomment-416025397) určitě myšlenej takhle?

**Comment by tomasfejfar** [comment]
Dobrá otázka. Já mám pocit, že @padak to popisoval (možná to bylo osobně, nebo na slacku) tak, že mají toho standardního writer usera. Tím v plní to schéma, ale potřebovali by mít možnost frantovi z accountingu dát k tomu schématu taky přístup, aby tam doplnil nějaké svoje věci. Ale možná jsem to pochopil špatně já. A mělo to být nějaké extra schéma pro toho uživatele. 

Ale pak nechápu v čem by to bylo lepší, než 
a) mít extra schéma a frantovi dát toho "schema usera" a jeho heslo
b) použít na tohle franovo schéma, kam má přístup pro zápis už těď

**Comment by Halama** [comment]
To mi právě zní dost divně to `doplnil nějaké svoje věci`. Možná  k tomu teda někde proběhla nějaká diskuze. Takhle bez kontextu a pospaného use casu mi to zatím moc nedává smysl.

**Comment by tomasfejfar** [comment]
Pingnul jsem to padákovi ještě slackem, kdyby nekoukal na notifikace a uvidíme. Je určitě možné, že jsem to jen nedomyslel. Ještě že ty review máme :)

**Comment by padak** [comment]
@tomasfejfar je tam typo. Chtěl jsem napsat "... pro které má write" a místo toho napsal "...pro které má writer". Prostě moct do schémat zapisovat a k tomu využít i víc různých lidí tak, aby když někam tři potřebují zapisovat, šlo je z toho snadno odpojit. De-facto stejnej důvod jako pro READ práva.

**Comment by Halama** [comment]
ok, teď to dává smysl.

**Comment by ondrejhlavacek** [comment]
Chápu ten use case tak, že uživatel s write zápisem nakonfiguruje writer tak, že bude do sdílenýho schématu zapisovat? (Samo kromě možnosti zapisovat do vlastního schématu)

**Comment by padak** [comment]
JJ, nebo vyrobí WRITE práva pro skutečnýho člověka, ne nutně KBC Writer.

**Comment by ondrejhlavacek** [comment]
Kdyby to teda nebyl writer, jak tam uživatel bude sypat data?

**Comment by Halama** [comment]
netuším

**Comment by Halama** [comment]
ale představuju že mají třeba RO schém kam sype data writer a pak mají svůj společný WRITE workspace kam si mohou tahat tabulky z toho writeru a něco si tam prasit:)

**Comment by padak** [comment]
typickej usecase je, že dva lidi maj něco spolu sdílet, na něčem makat dohromady - potřebují schema na write

nebo maj python bazmek, co se má někam připojit a něco v tom udělat

nebo maj tři KBC projekty a potřebují z každého na jedno místo nasypat pár tabulek, aby s nima něco dál pracovalo

**Comment by ondrejhlavacek** [comment]
> nebo maj tři KBC projekty a potřebují z každého na jedno místo nasypat pár tabulek, aby s nima něco dál pracovalo

na to by byly lepší servisní credentials, ne? když toho uživatele vyhodí, přestane tahle integrace fungovat a bude se setupovat na nějakýho jinýho uživatele

> nebo maj python bazmek, co se má někam připojit a něco v tom udělat

taky servisní uživatel?

> typickej usecase je, že dva lidi maj něco spolu sdílet, na něčem makat dohromady - potřebují schema na write

tohle dává smysl!

**Comment by padak** [comment]
schopnost aby si založenej writer "somehow" vzal credentials z tohohle manageru a tys to nemusel copy&pastovat (a tím pádem mít ve firmě člověka, co ty credentials zná), by bylo cool! Teď musíš jít a ještě se pod nima přihlásit abys je změnil a pak podle nich nastavit writer

**Comment by ondrejhlavacek** [comment]
cajk, jen jsem chtěl připomenout, že tohle je furt prototyp :-)

**Comment by padak** [comment]
jj, to vím. Ale když tam nabušíme RW, nebudeme to muset vymejšlet pak - není to zbytečná investice, ne? :)

**Comment by ondrejhlavacek** [comment]
to jsem tím vůbec nemyslel! naopak tohle je na to dobrej playground. chceš https://github.com/keboola/app-snowflake-dwh-manager/issues/13#issuecomment-423105020 řešit dál tady, zavolat si nebo se třeba potkat?

**Comment by padak** [comment]
ne, servisní accounty bych teď nechal (chvilku) bejt. jde mi fakt "jen" o možnost přidat k RO schematu i RW schema.

**Comment by ondrejhlavacek** [comment]
no právě si nejsem jistej, jestli je dobrý to takhle hnedka zahodit - mně přijde, že většina popsanejch use casů je spíš na servisní account a nemuselo by se to zanést bordelem typu login uživatele ve writeru nebo python transformaci, ze kterýho se bude dost blbě vybrušovat a bude se ještě víc narážet hlavou při známejch nepodporovanejch situacích.

pro *typickej usecase je, že dva lidi maj něco spolu sdílet, na něčem makat dohromady - potřebují schema na write* si to ale dokážu představit jak popisuješ! pokud bys k tomu klientovi dokázal říct, ať to nezneužívá na writery z jinejch projektů nebo to nesype do python bazmeku/transformace, je to ok!
