### ISSUE TITLE
No error message

### ISSUE THREAD

**Issue by odinuv** [keboola/app-snowflake-dwh-manager#14]
https://papertrailapp.com/groups/170211/events?focus=971106733399363668&selected=971106733399363668

vubec nic to nenapsalo, jediny voditko je exit kod 139:

```
{
    "output": "",
    "errorOutput": "",
    "container": {
        "id": "7584998-7584999-7584749-0-keboola-app-snowflake-dwh-manager",
        "image": "147946154733.dkr.ecr.us-east-1.amazonaws.com\/developer-portal-v2\/keboola.app-snowflake-dwh-manager:2.0.0"
    }
}
```

**Comment by tomasfejfar** [comment]
Na linuxu by exit kódy > 128 měly být jako 128+X, kde X je číslo signálu, který proces ukončil. V tomhle případě to vychází na 11. A SIG11 je segfault. Takže to je nejspíš segfault v PHP nebo v dockeru.

**Comment by ondrejhlavacek** [comment]
Nepadala v tu dobu instance náhodou? Segfaulty driveru jsou tuším vidět v PT, ale jen v raw seznamu, ne u jobu.

**Comment by Halama** [comment]
Mrknul jsem a nepadala, nemusel to byt segfault driveru ale primo PHP.

**Comment by tomasfejfar** [comment]
Děle se to relativně často a pořád u jedné konfigurace. Jdu prověřit, co je to zač. 

https://papertrailapp.com/groups/23635/events?q=%22keboola-app-snowflake-dwh-manager%27%20failed%22

**Comment by tomasfejfar** [comment]
Děje se to jen u jednoho configu. A děje se to pro různé rows a různě dlouho po začátku (row 18, 20, 28 z 53). Tj. někdy to na té row chcípne a jindy je to v pohodě. To mě vede k úvaze, že to nejspíš není způsobované něčím v konfiguraci nebo v komponentě. 

```
SELECT * FROM "in.c-sapi-eu.component-configuration-rows" WHERE
"idProject" = 196 
AND "configurationId" = 4121312 
AND "configurationVersion_to" = ''
AND "rowId" in (9352904, 7163875, 9354505 )
```
Runids: 
10623853.10623864
11322782.11322803
11225475.11225490

Máte nějaké nápady co dál s tím?

**Comment by Halama** [comment]
začal bych updatem driveru

**Comment by ondrejhlavacek** [comment]
Ten driver je asi nejsnazší. Další možnost - našel bych odpovídající session v query history (tabulka je taky v Shared configu) a podíval se, jaká byla poslední query (jestli byla vždy stejná, skončila successem nebo errorem, jestli je čas segfaultu během exekuce query nebo po ní, atd.).

**Comment by tomasfejfar** [comment]
Driver je aktuální. 
![image](https://user-images.githubusercontent.com/642928/47087343-06373a00-d21c-11e8-952a-9937d47a473b.png)

```
λ aws s3 ls keboola-drivers/snowflake/
2018-10-01 09:03:35   17885046 snowflake-odbc-2.16.10.x86_64.deb
```

**Comment by Halama** [comment]
Ale v téhle appce vidím 2.14.0 https://github.com/keboola/app-snowflake-dwh-manager/blob/c91ac91a63b6019a68e5f67e6774f5e648505803/Dockerfile#L4

**Comment by tomasfejfar** [comment]
OMFG. Jsem idiot. Díky. Rovnou to tam předělám na ten nový způsob.

**Comment by tomasfejfar** [comment]
Ref.: https://github.com/keboola/app-snowflake-dwh-manager/pull/19

Uvidíme, jestli to pomůže.

**Comment by tomasfejfar** [comment]
Opět to nastalo `docker-9cf83273fa2defe809cd418d31867fe3`

**Comment by tomasfejfar** [comment]
Od té doby nejspíš už nenastává, takže zavírám.
