### ISSUE TITLE
Při zakládání nové "row" to ukáže občas JSON editor

### ISSUE THREAD

**Issue by padak** [keboola/app-snowflake-dwh-manager#16]
místo aby to ukázalo formulář. Blbě se to reprodukuje... Hlásí to Ondra z Avastu, kterej kliká 32 holek.

**Comment by tomasfejfar** [comment]
Stalo se mi to při vývoji UI taky několikrát ze začátku. Ale pak už se mi to nepodařilo zreplikovat, tak jsem předpokládal, že se to vyřešilo tím, že jsem někde něco změnil. 

Každopádně by se hodilo aspoň poslat konfigurák, který to hodí do JSONu  a popis toho co měnil nebo něco od čeho se můžu odpíchnout. Takhle s tím nedokážu asi nic udělat.

**Comment by tomasfejfar** [comment]
Aha, uf. Zkusím to prověřit.

**Comment by tomasfejfar** [comment]
A je to US nebo EU?

**Comment by padak** [comment]
Tady na tom: https://connection.eu-central-1.keboola.com/admin/projects/82/applications/keboola.app-snowflake-dwh-manager/9130846

**Comment by tomasfejfar** [comment]
To, že má prázdný JSON by se nemělo vůbec stát. To by nemělo vůbec jít. Ve výchozím stavu by měl v tom JSONu už mít nastavené schéma s názvem vytaženým z názvu té row. 

Stará se o to [tady ten kus kódu] a o kus níž je nastavení, že by default je to schéma - proto by to s "nic" mělo spadnout na ten zalinkovaný kus kódu. Nenapadá vás kluci, co by to mohlo způsobit? @ujovlado @kacurez ?

**Comment by ondrejhlavacek** [comment]
UI jsem dělal já, to bude na mě. Mrknu.

**Comment by kacurez** [comment]
to je zvlastne, tak z fleku ma nic nenapada. Asi nema zmysel aby sme to debugovali dvaja, takze to zatial necham tak ale pingnite ma ak by ste nanic neprisli.

**Comment by ondrejhlavacek** [comment]
@padak jediný, co mě napadá je, že by v UI neměl ještě správně načtený config, který se odeslal. Mohl by zkusit, až se to znovu stane, jen stránku reloadnout, jestli se to nezobrazí správně? A nevzpomněl by si, při jakým accountu se mu to stalo? Naklonoval bych si v tý verzi config a mrknul, jak se to mohlo stát - teď je tam 100+ verzí a po jedný to dělat nejde.

**Comment by padak** [comment]
to si asi nevzpomene - řekl mi to úplně na konci a dělal jich tam asi 40 :( Tak to nechme chvilku bejt, v Mallu do toho teď budou kopat a HCVN asi taky - tak uvidíme

**Comment by ondrejhlavacek** [comment]
Ok, nechám otevřený a budu čekat na další info. Dík

**Comment by tomasfejfar** [comment]
JFYI: Zkusil jsem to přímo na tom projektu už předtím replikovat a [CNR](https://xkcd.com/583/) - zkusil jsem vytvořit spoustu rows a zas je zahodil a nic. Teoreticky by to mohla být nějaká race condition, která se projeví jen, když člověk sedí na páteřní lince a GLAN, jako to mají asi v Mallu.

**Comment by ondrejhlavacek** [comment]
jj, to jsem myslel tím 
> že by v UI neměl ještě správně načtený config, který se odeslal

**Comment by ujovlado** [comment]
v Chrome sa da nastavit throttling, skus si dat len par kB a uvidi sa  :)

**Comment by tomasfejfar** [comment]
No, ale já to potřebuju opačně, ne? Potřebuju, aby to bylo rychlejší, než se zpracuje ten request v KBC.

**Comment by ondrejhlavacek** [comment]
UI by na odpověď mělo čekat.

**Comment by tomasfejfar** [comment]
jj, schválně jsem to zkusil a čeká to na odpověd.

**Comment by ondrejhlavacek** [comment]
@tomasfejfar víc času na tom zbytečně nepal, tohle bych měl mít pod palcem já :-)

**Comment by ondrejhlavacek** [comment]
Jestli tě štve otevřená issue, přesunem jí do `kbc-ui` :-)

**Comment by tomasfejfar** [comment]
nn, np...

**Comment by ondrejhlavacek** [comment]
Přesunul bych to do kbc-ui, stává se to i v jiných appkách.

**Comment by ondrejhlavacek** [comment]
https://github.com/keboola/kbc-ui/issues/2546
