### ISSUE TITLE
Lower data retention

### ISSUE THREAD

**Issue by tomasfejfar** [keboola/app-snowflake-dwh-manager#24]
Ref.: https://keboola.slack.com/archives/C0308KGPP/p1542910817015600

**Comment by tomasfejfar** [comment]
Že to funguje jsem otestoval takto:

```
CREATE DATABASE "DWHM_TEST1" DATA_RETENTION_TIME_IN_DAYS = 0;
USE DATABASE "DWHM_TEST1";
CREATE SCHEMA DWHM_TEST ;
USE SCHEMA DWHM_TEST;
CREATE TABLE test (id int);
SHOW TABLES;
DROP DATABASE "DWHM_TEST1";
```

Případně můžeme na produkci nastavit ty existující pokud nejsou, ale radši jsem to zatím nepouštěl, netuším jestli to někde není jinak schválně.

```
SHOW DATABASES LIKE 'DWHM_%';
// foreach
GRANT ROLE DWHM_WHATEVER TO ROLE ACCOUNTADMIN;
ALTER DATABASE DWHM_WHATEVER SET DATA_RETENTION_TIME_IN_DAYS = 0;
REVOKE ROLE DWHM_WHATEVER FROM ROLE ACCOUNTADMIN;
```

Ale někdo (@padak ?) musí říct, jestli to mám nastavit u všech, případně u kterých ne...

**Comment by padak** [comment]
@tomasfejfar promiň, v závalu emailů mi ta notifikace zapadla. Ano, všude bych začal s tím, že je to TRANSIENT, případně stejně jako v KBC - 7 dní. Pokud je to pro tebe úplně jedno, tak 7 dní je můj winner (lidi to maj ve smlouvě). HC bude mít 30, myslím - dal bych jim taky 7, ale čekal na to, že to budou chtít zvednout, tak aby to šlo nastavovat.

**Comment by tomasfejfar** [comment]
Mě je to úplně jedno. 

TRANSIENT mi z pohledu klienta přijde možná až moc. Měsíc si něco šudlám ve schématu a pak si to omylem smažu. Tak by se mi asi hodilo mít možnost to obnovit. Time travel nad tím asi smysl tolik nedává. Tím, že je to takový "vývojový" mód mi to nepřijde nutné. 

7 dní mi přijde, že je docela štědré, ale jestli to není problém z hlediska financí, tak proč ne.

**Comment by padak** [comment]
ok, dejme 7 dní

**Comment by tomasfejfar** [comment]
Aktuální query pro úpravu na domluvených 7 dní:

```
SET dwhm_db = '"TF2_DWH_MANAGER"';

SET (current_role) = (SELECT CURRENT_ROLE());

GRANT ROLE IDENTIFIER($dwhm_db) TO ROLE IDENTIFIER($current_role);
ALTER DATABASE IDENTIFIER($dwhm_db) SET DATA_RETENTION_TIME_IN_DAYS = 7;
REVOKE ROLE IDENTIFIER($dwhm_db) FROM ROLE IDENTIFIER($current_role);
```
