### ISSUE TITLE
Snowflake binding

### ISSUE THREAD

**Issue by Halama** [keboola/app-snowflake-dwh-manager#3]
Moc nevím kam to hodit, tak to dávám sem pro další debug. 

Ideální by bylo předávat všechny identifikátory přes binding a [identifier](https://docs.snowflake.net/manuals/sql-reference/identifier-literal.html):
`$connection->query("CREATE TABLE IDENTIFIER(?)", ['martin']);`

Bohužel to končí:
`odbc_prepare(): SQL error: SQL compilation error: syntax error line 1 at position 26 unexpected '<EOF>'`
![image](https://user-images.githubusercontent.com/903531/41464259-f4823460-7099-11e8-8b8b-1b81dcfbc528.png)

Vypadá to jakoby to fungovalo jenom pro `SELECT`
`$connection->query('SELECT ?', ['1']);` projde ok.

![image](https://user-images.githubusercontent.com/903531/41464329-31716a76-709a-11e8-8e4f-c77230237055.png)

https://docs.snowflake.net/manuals/user-guide/odbc-api.html

**Comment by tomasfejfar** [comment]
Já jsem to taky zkoušel ve výsledku celé přepsat na `IDENTIFIER()`, ale moc to nefungovalo. Moje pochopení je, že to není filtr, který převede string na něco co by mohlo být identifier, ale je překladač string  → EXISTUJÍCÍ identifier. Takže nejde využít na vytváření.

**Comment by Halama** [comment]
Mě to bez toho ODBC na vytváření funguje, např. v UI spuštěné.
`create table identifier('"radnom-pokus"') (a varchar);`
Problém je asi v tom bindingu. Stejně to ale vypadá že na sloupce to fungovat nebude.

**Comment by tomasfejfar** [comment]
```
create table "MY-DWH1" (pk INT);

SELECT * FROM IDENTIFIER('my-dwh1'); // ne
SELECT * FROM IDENTIFIER('MY-DWH1'); // ne
SELECT * FROM IDENTIFIER('"MY-DWH1"'); // ano
SELECT * FROM IDENTIFIER('"my-dwh1"'); // ano

create table "MY_DWH1" (pk INT);
SELECT * FROM IDENTIFIER('my_dwh1'); // ano
SELECT * FROM IDENTIFIER('"MY_DWH1"'); // ano
SELECT * FROM IDENTIFIER('"my_dwh1"'); // ano
```

**Comment by Halama** [comment]
Je to vidět i v tech examples tady https://docs.snowflake.net/manuals/sql-reference/identifier-literal.html  Jenom těm sloupcům se tam vyhýbají:)

**Comment by Halama** [comment]
jj to sedí  s tím co tam píšou v doc `MY-DWH1` není validní, musí být quoted.

**Comment by tomasfejfar** [comment]
No, ale to bych čekal, že udělá za mě.

**Comment by Halama** [comment]
jo taky jsem si původně myslel že to udělá, ale ne.

**Comment by Halama** [comment]
protože on opět zas akceptuje i fully qualified names a z toho by nevěděl jak to má oquotovat.

**Comment by Halama** [comment]
takže jediná výhoda je v tom že by to mohlo jít přes ten bind, který ale nefunguje :)

**Comment by Halama** [comment]
stejně je předtím potřeba to obalit do uvozovek vždy.

**Comment by tomasfejfar** [comment]
> takže jediná výhoda je v tom že by to mohlo jít přes ten bind, který ale nefunguje :)

Jo, přesně tak bych to shrnul :D

**Comment by Halama** [comment]
btw. hodil sem to issue teď jenom protože jsem to v rychlosti vyzkoušel. Nemusí se teď řešit...
Na ten bind by bylo dobré se pak zeptat na support asi. Možná to je zas nějaká "feature" odbc...

**Comment by tomasfejfar** [comment]
Jo, já to úplně "neřeším", ale spíš by se mi to hodilo. Ale tak jak to je je to asi good-enough a tohle můžu vyřešit, až DWHM bude v produkci.

**Comment by tomasfejfar** [comment]
Ref.: https://keboola.slack.com/archives/C0308KGPP/p1543323358037100?thread_ts=1543316594.029300&cid=C0308KGPP

**Comment by Halama** [comment]
Pokračujme v https://github.com/keboola/php-db-import/issues/45
